repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: bandit
        name: scanning for security issues
        description: https://github.com/PyCQA/bandit
        entry: bandit
        args: [ '-c', 'pyproject.toml' ]
        language: python
        types: [ python ]
        exclude: (conftest.py|setup.py|docs/source/conf.py)
      - id: flake8
        name: code linting
        description: https://github.com/PyCQA/flake8
        entry: pflake8
        args: [ '--doctests', '--config', 'pyproject.toml']
        language: python
        types: [ python ]
        exclude: (conftest.py|setup.py|docs/source/conf.py)
        require_serial: true
      - id: pydocstyle
        name: docstrings linting
        description: https://github.com/PyCQA/pydocstyle
        entry: pydocstyle
        args: [ '--config', 'pyproject.toml']
        language: python
        types: [ python ]
        exclude: (conftest.py|setup.py|docs/source/conf.py)
      - id: rst-lint
        name: RST linting
        description: https://github.com/twolfson/restructuredtext-lint
        entry: rst-lint
        language: system
        types: [ rst ]
        exclude: docs/source/
      - id: shellcheck
        name: shell scripts linting
        description: https://github.com/shellcheck-py/shellcheck-py
        entry: shellcheck
        args: ['-e', 'SC1091', '-e', 'SC2015', '-e', 'SC2035']
        language: python
        types: [ shell ]
        files: tools/
        require_serial: true
      - id: pyroma
        name: setup files linting
        description: https://github.com/regebro/pyroma
        entry: pyroma
        args: [ '-d', '--min=9', '.' ]
        language: python
        files: setup.cfg
        pass_filenames: false
