[tox]
{% set versions = cookiecutter.python_versions.split('_') -%}
envlist = {%- for v in versions %}py3{{ v }},{% endfor %}
skip_missing_interpreters = true

[testenv]
deps =
    -r requirements/dev.txt
commands = python -m pytest
